import org.antlr.v4.runtime.ANTLRInputStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.*;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.IOException;

/**
 * The main driver for the C to Python translator.
 * This class sets up the ANTLR parsing pipeline:
 * 1. Reads a C source file.
 * 2. Creates a lexer to tokenize the input.
 * 3. Creates a parser to build a parse tree.
 * 4. Instantiates our custom listener, CToPythonListener.
 * 5. Uses a ParseTreeWalker to traverse the tree with the listener.
 * 6. Prints the final translated Python code generated by the listener.
 */
public class CTranslator {
    public static void main(String[] args) throws Exception {
        if (args.length == 0) {
            System.err.println("Usage: java CTranslator <c-source-file>");
            return;
        }
        String inputFile = args[0];

        InputStream is = System.in;
        if ( inputFile!=null ) {
            is = new FileInputStream(inputFile);
        }

        ANTLRInputStream input = new ANTLRInputStream(is);
        CLexer lexer = new CLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        CParser parser = new CParser(tokens);
        ParseTree tree = parser.compilationUnit();
        ParseTreeWalker walker = new ParseTreeWalker();
        CToPythonListener listener = new CToPythonListener(parser);
        walker.walk(listener, tree);

        // Output the generated Python code
        System.out.println(listener.getPythonCode());

    }
}